{
    "openapi": "3.0.0",
    "info": {
        "title": "DEC",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:8001/api/",
            "description": "DEV"
        }
    ],
    "paths": {
        "/auth": {},
        "/register": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Criar novo usuário",
                "description": "Cria novo usuário: Administradores podem criar qualquer tipo de usuário, Gerentes podem criar REPRESENTANTES, Representantes podem criar MEMBROS E VISUALIZADORES",
                "operationId": "0903f2e0df1a8857bee538fc055417f0",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "example": {
                                    "name": "Nome do usuário",
                                    "email": "Email do usuário",
                                    "password": "Senha do usuário",
                                    "c_password": "Confirmação de senha",
                                    "type_user_id": "ID do tipo de usuário"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "422": {
                        "description": "Erro de validação"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Login do usuário",
                "description": "Usuário loga no sistema",
                "operationId": "2dd578ff7aba2721293dac66833b27d1",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "example": {
                                    "email": "Email do usuário",
                                    "password": "Senha do usuário"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "422": {
                        "description": "Erro de validação"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/users/logout": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Desloga usuário",
                "description": "Endpoint para revogar o token",
                "operationId": "4d05b3b4c4627a89a3d62ea61d7aff88",
                "responses": {
                    "204": {
                        "description": "Not Content"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            }
        },
        "/documents": {
            "get": {
                "tags": [
                    "documents"
                ],
                "summary": "Listar todos os membros",
                "description": "Lista todos os membros: ADMINISTRADOR, REPRESENTANTE E GERENTE têm acesso a este endpoint.",
                "operationId": "cf58d1781992e8292fd9914b24487fdc",
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Erro"
                    },
                    "403": {
                        "description": "Não autorizado"
                    }
                }
            }
        },
        "/documents/{id}": {
            "get": {
                "tags": [
                    "documents"
                ],
                "summary": "Lista o registro de documento por ID",
                "description": "Lista o registro de documento por ID de referência",
                "operationId": "9cf5289c9ad15ddb6da247477998f54b",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do documento",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "404": {
                        "description": "Membro not found"
                    },
                    "200": {
                        "description": "Ok"
                    },
                    "403": {
                        "description": "Não autorizado"
                    }
                }
            },
            "put": {
                "tags": [
                    "documents"
                ],
                "summary": "Atualiza documentos",
                "description": "Atualizar documentos: somente o REPRESENTANTE tem acesso a este endpoint.",
                "operationId": "8340a1a99f82c944b6c7b45b0794505f",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do documento",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "properties": {
                                    "description": {
                                        "description": "descrição do documento",
                                        "type": "string"
                                    },
                                    "file": {
                                        "description": "anexo da tarefa",
                                        "type": "file"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Erro"
                    },
                    "403": {
                        "description": "Não autorizado"
                    },
                    "404": {
                        "description": "Membro not found"
                    }
                }
            }
        },
        "/group/{groupId}/documents": {
            "post": {
                "tags": [
                    "documents"
                ],
                "summary": "Criar novo documento",
                "description": "Cria um novo documento, somente o REPRESENTANTE tem acesso a este endpoint.",
                "operationId": "3beed3e3aeaa9b0a0a5ea431400b26d0",
                "parameters": [
                    {
                        "name": "groupId",
                        "in": "path",
                        "description": "Id do grupo que o documento sera associado",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "properties": {
                                    "description": {
                                        "description": "descrição do documento",
                                        "type": "string"
                                    },
                                    "file": {
                                        "description": "documento a ser anexado",
                                        "type": "file"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Criado"
                    },
                    "500": {
                        "description": "Erro"
                    },
                    "422": {
                        "description": "Erro de validação"
                    },
                    "403": {
                        "description": "Não autorizado"
                    }
                }
            }
        },
        "/group/{groupId}/documents/{documentId}": {
            "delete": {
                "tags": [
                    "documents"
                ],
                "summary": "Deletar documento",
                "description": "Deletar documento por ID de referência, somente o REPRESENTANTE tem acesso a este endpoint.",
                "operationId": "2b113906220faa6735e222ca942fde22",
                "parameters": [
                    {
                        "name": "groupId",
                        "in": "path",
                        "description": "Id do grupo",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "documentId",
                        "in": "path",
                        "description": "Id do documento",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Erro"
                    },
                    "403": {
                        "description": "Não autorizado"
                    }
                }
            }
        },
        "/group": {
            "get": {
                "tags": [
                    "group"
                ],
                "summary": "Listar todos os grupos",
                "description": "Lista todos os grupos",
                "operationId": "e8330ffe5396478cbf1a2fb8a8cf0536",
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    }
                }
            },
            "post": {
                "tags": [
                    "group"
                ],
                "summary": "Criar novo grupo",
                "description": "Cria novo grupo",
                "operationId": "e4177fdb8c798f4607f383faade958a2",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "representatives": {
                                        "type": "array",
                                        "items": {
                                            "type": "integer"
                                        },
                                        "example": [
                                            2,
                                            4
                                        ]
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "entity": "exercitationem",
                                    "organ": "architecto",
                                    "council": "voluptates",
                                    "acronym": "nesciunt",
                                    "team": "ut",
                                    "unit": "occaecati",
                                    "email": "amanda24@hotmail.com",
                                    "office_requested": "accusamus",
                                    "office_indicated": "incidunt",
                                    "internal_concierge": "corrupti",
                                    "type_group_id": 1,
                                    "observations": "Repellendus aut voluptatem quaerat consequuntur illum. Dolor est sed natus est. Qui voluptatibus iure necessitatibus velit.",
                                    "representatives": [
                                        2,
                                        4
                                    ]
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "422": {
                        "description": "Erro de validação"
                    },
                    "403": {
                        "description": "Unauthorized"
                    },
                    "400": {
                        "description": "Apenas usuarios do tipo representante sao permitidos"
                    }
                }
            }
        },
        "/group/{id}": {
            "get": {
                "tags": [
                    "group"
                ],
                "summary": "Lista o registro de grupos por ID",
                "description": "Lista o registro de grupos por ID de referência",
                "operationId": "493ecdf27d6748ca0f27a2647e91c9dd",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do grupo",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "404": {
                        "description": "grupo not found"
                    },
                    "200": {
                        "description": "Ok"
                    },
                    "403": {
                        "description": "Unauthorized"
                    }
                }
            },
            "put": {
                "tags": [
                    "group"
                ],
                "summary": "Atualizar grupo",
                "description": "Atualizar grupo",
                "operationId": "f75f2cc8da4d387333b87c85e463dcf4",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do grupo",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "representatives": {
                                        "type": "array",
                                        "items": {
                                            "type": "integer"
                                        },
                                        "example": [
                                            2,
                                            4
                                        ]
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "entity": "exercitationem",
                                    "organ": "architecto",
                                    "council": "voluptates",
                                    "acronym": "nesciunt",
                                    "team": "ut",
                                    "unit": "occaecati",
                                    "email": "amanda24@hotmail.com",
                                    "office_requested": "accusamus",
                                    "office_indicated": "incidunt",
                                    "internal_concierge": "corrupti",
                                    "type_group_id": 1,
                                    "observations": "Repellendus aut voluptatem quaerat consequuntur illum. Dolor est sed natus est. Qui voluptatibus iure necessitatibus velit.",
                                    "representatives": [
                                        2,
                                        4
                                    ]
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Usuário not found"
                    },
                    "400": {
                        "description": "Apenas usuarios do tipo representante sao permitidos"
                    }
                }
            },
            "delete": {
                "tags": [
                    "group"
                ],
                "summary": "Deletar grupo",
                "description": "Deletargrupo por ID de referência",
                "operationId": "46eb6481112edc002da8139e138951b2",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do grupo",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "grupo Not Found"
                    }
                }
            }
        },
        "/members": {
            "get": {
                "tags": [
                    "members"
                ],
                "summary": "Listar todos os membros",
                "description": "Lista todos os membros: ADMINISTRADOR, REPRESENTANTE E GERENTE têm acesso a este endpoint.",
                "operationId": "0a7045fbb9a3c713742cb2ed937a0105",
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Erro"
                    },
                    "403": {
                        "description": "Não autorizado"
                    }
                }
            }
        },
        "/group/{groupId}/members": {
            "post": {
                "tags": [
                    "members"
                ],
                "summary": "Criar novo membro",
                "description": "Cria um novo membro, somente o REPRESENTANTE tem acesso a este endpoint.",
                "operationId": "132ca5b0db7a8673ae8bea65a2eed21f",
                "parameters": [
                    {
                        "name": "groupId",
                        "in": "path",
                        "description": "Id do grupo que o membro sera associado",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "example": [
                                    {
                                        "role": "bar",
                                        "phone": "93991185489",
                                        "entry_date": "23-10-1998",
                                        "departure_date": "23-10-2023",
                                        "user_id": "1"
                                    },
                                    {
                                        "role": "bar",
                                        "phone": "93991185489",
                                        "entry_date": "23-10-1998",
                                        "departure_date": "23-10-2023",
                                        "user_id": "2"
                                    }
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Criado"
                    },
                    "500": {
                        "description": "Erro"
                    },
                    "422": {
                        "description": "Erro de validação"
                    },
                    "403": {
                        "description": "Não autorizado"
                    }
                }
            }
        },
        "/members/{id}": {
            "get": {
                "tags": [
                    "members"
                ],
                "summary": "Lista o registro de membro por ID",
                "description": "Lista o registro de membro por ID de referência.",
                "operationId": "1fd856fdfaaf1e386c20f99e657e1904",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do membro",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "404": {
                        "description": "Membro not found"
                    },
                    "200": {
                        "description": "Ok"
                    },
                    "403": {
                        "description": "Não autorizado"
                    }
                }
            },
            "put": {
                "tags": [
                    "members"
                ],
                "summary": "Atualizar membro",
                "description": "somente o REPRESENTANTE tem acesso a este endpoint.",
                "operationId": "abf8609c946a1cf6b1fc64a55b707dc6",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do membro",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "role": {
                                        "description": "O papel do membro.",
                                        "type": "string"
                                    },
                                    "phone": {
                                        "description": "O número de telefone do membro (deve ter pelo menos 11 caracteres).",
                                        "type": "string"
                                    },
                                    "departure_date": {
                                        "description": "A data de partida do membro (formato YYYY-MM-DD).",
                                        "type": "string",
                                        "format": "date"
                                    },
                                    "user_id": {
                                        "description": "O ID do usuário associado ao membro.",
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Erro"
                    },
                    "403": {
                        "description": "Não autorizado"
                    },
                    "404": {
                        "description": "Membro not found"
                    }
                }
            }
        },
        "/group/{groupId}/members/{memberID}": {
            "delete": {
                "tags": [
                    "members"
                ],
                "summary": "Deletar membro",
                "description": "Deletar membro por ID de referência, somente o REPRESENTANTE tem acesso a este endpoint.",
                "operationId": "b6a3e4aad017899e4a380903c4192d66",
                "parameters": [
                    {
                        "name": "groupId",
                        "in": "path",
                        "description": "Id do grupo",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "memberId",
                        "in": "path",
                        "description": "Id do membro",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Erro"
                    },
                    "403": {
                        "description": "Não autorizado"
                    }
                }
            }
        },
        "/type-group": {
            "get": {
                "tags": [
                    "type-group"
                ],
                "summary": "Listar todos os tipos de grupos",
                "description": "Lista todos os tipos de grupos",
                "operationId": "bb4211d238dc2ccef7e751e0f0ab53fa",
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    }
                }
            },
            "post": {
                "tags": [
                    "type-group"
                ],
                "summary": "Criar novo tipo de grupo",
                "description": "Cria novo tipo de grupo",
                "operationId": "681c9bc3e5c6e6fd9d969ffe21b64589",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "example": {
                                    "name": "Nome do grupo",
                                    "type_group": "Tipo de grupo: Interno ou Externo"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "422": {
                        "description": "Erro de validação"
                    },
                    "403": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/type-group/{id}": {
            "get": {
                "tags": [
                    "type-group"
                ],
                "summary": "Lista o registro de tipos de grupos por ID",
                "description": "Lista o registro de tipos de grupos por ID de referência",
                "operationId": "e0a9ca31b284b1126b3c325b0a0ce29f",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do tipo de grupo",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "404": {
                        "description": "Tipo de grupo not found"
                    },
                    "200": {
                        "description": "Ok"
                    },
                    "403": {
                        "description": "Unauthorized"
                    }
                }
            },
            "put": {
                "tags": [
                    "type-group"
                ],
                "summary": "Atualizar tipo de grupo",
                "description": "Atualizar tipo de grupo",
                "operationId": "c430e30b45e1fca42948eb45fc36a01e",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do tipo de grupo",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "example": {
                                    "name": "Nome do tipo de grupo",
                                    "type_group": "Tipo de grupo: Interno ou Externo"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Usuário not found"
                    }
                }
            },
            "delete": {
                "tags": [
                    "type-group"
                ],
                "summary": "Deletar tipo de grupo",
                "description": "Deletar tipo de grupo por ID de referência",
                "operationId": "cdd2cec033d8dae6ddf3854290fbc3cf",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do tipo de grupo",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Tipo de grupo Not Found"
                    }
                }
            }
        },
        "/type-user": {
            "get": {
                "tags": [
                    "type-user"
                ],
                "summary": "Listar todos os tipos de usuários",
                "description": "Lista todos os tipos de usuários",
                "operationId": "0658c79559e5f956adaf53d86cd7aae8",
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    }
                }
            },
            "post": {
                "tags": [
                    "type-user"
                ],
                "summary": "Criar novo tipo de usuário",
                "description": "Cria novo tipo de usuário",
                "operationId": "9b51073d4a14a8a9b77a1f80502b5397",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "example": {
                                    "name": "Nome do usuário"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "422": {
                        "description": "Erro de validação"
                    },
                    "403": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/type-user/{id}": {
            "get": {
                "tags": [
                    "type-user"
                ],
                "summary": "Lista o registro de tipos de usuários por ID",
                "description": "Lista o registro de tipos de usuários por ID de referência",
                "operationId": "8b966620ece503726bb2622036470b76",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do tipo de usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "404": {
                        "description": "Tipo de usuário not found"
                    },
                    "200": {
                        "description": "Ok"
                    },
                    "403": {
                        "description": "Unauthorized"
                    }
                }
            },
            "put": {
                "tags": [
                    "type-user"
                ],
                "summary": "Atualizar tipo de usuário",
                "description": "Atualizar tipo de usuário",
                "operationId": "e3915ed9a4f9caca167f43217a4ac7e0",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do tipo de usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "example": {
                                    "name": "Nome do tipo de usuário"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Usuário not found"
                    }
                }
            },
            "delete": {
                "tags": [
                    "type-user"
                ],
                "summary": "Deletar tipo de usuário",
                "description": "Deletar tipo de usuário por ID de referência",
                "operationId": "ac413f3a4d4d6b72726009645f379fe0",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do tipo de usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Tipo de usuário Not Found"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "Listar todos os usuários",
                "description": "Lista todos os usuários: 3 tipos de usuários obtem o acesso desse endpoint: ADMINISTRADOR, REPRESENTANTE E GERENTE",
                "operationId": "7e2f5799553ec93c9c43e2a58490d447",
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "Lista o registro de usuários por ID",
                "description": "Lista o registro de usuários por ID de referência",
                "operationId": "910a0c7cf580e1c605648d82a4e57f46",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "404": {
                        "description": "Usuário not found"
                    },
                    "200": {
                        "description": "Ok"
                    },
                    "403": {
                        "description": "Unauthorized"
                    }
                }
            },
            "put": {
                "tags": [
                    "users"
                ],
                "summary": "Atualizar usuário",
                "description": "Atualizar usuário: Apenas o usuário pode atualizar suas próprias informações ou o usuário que o criou",
                "operationId": "ddfe232db1870b82493bf8bd25596d37",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "example": {
                                    "name": "Nome do usuário",
                                    "email": "Email do usuário",
                                    "password": "Senha do usuário"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Usuário not found"
                    }
                }
            },
            "delete": {
                "tags": [
                    "users"
                ],
                "summary": "Deletar usuário",
                "description": "Deletar usuário por ID de referência: Apenas o usuário pode deletar suas próprias informações ou o usuário que o criou",
                "operationId": "43dd20becb1f47444e484cbb18ce345c",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "403": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Usuario Not Found"
                    }
                }
            }
        },
        "/users/restore/{id}": {
            "patch": {
                "tags": [
                    "users"
                ],
                "summary": "Restaurar usuário",
                "description": "Restaurar usuário: Apenas o usuário pode restaurar suas próprias informações ou o usuário que o criou",
                "operationId": "282df5354ee2b04bf7ac4bbc6d5fb515",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do usuário",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok"
                    },
                    "500": {
                        "description": "Error"
                    },
                    "404": {
                        "description": "Usuário not found"
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "Authorization": {
                "type": "apiKey",
                "name": "Authorization",
                "in": "header"
            }
        }
    },
    "security": [
        {
            "Authorization": []
        }
    ],
    "tags": [
        {
            "name": "auth",
            "description": "Autenticação dos usuários"
        },
        {
            "name": "documents",
            "description": "CRUD dos documentos, apenas usuários do tipo REPRESENTANTES podem criar, atualizar e editar membros"
        },
        {
            "name": "group",
            "description": "Controle dos grupo: apenas usuários com o tipo de usuário GERENTE tem acesso aos endpoints de criação, deleção e atualizar"
        },
        {
            "name": "members",
            "description": "CRUD dos membros, apenas usuários do tipo REPRESENTANTES podem criar, atualizar e editar membros"
        },
        {
            "name": "type-group",
            "description": "Controle dos tipos de grupo: apenas usuários com o tipo de usuário GERENTE tem acesso a esses endpoints"
        },
        {
            "name": "type-user",
            "description": "Controle dos tipos de usuário: apenas usuários com o tipo de usuário ADMINISTRADOR tem acesso a esses endpoints"
        },
        {
            "name": "users",
            "description": "CRUD dos usuários"
        }
    ]
}